name: Test some shit
run-name: "{{ gitea.actor }} is running test"
on: [push]
env:
  VERSION: ${{ gitea.ref }}
jobs:
  Run-unit-tests:
     runs-on: docker
     steps:
        - name: Check out repo code
          uses: actions/checkout@v4
        - name: Login to Nexus
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.NEXUS_REPO }}
            username: ${{ secrets.NEXUS_USER }}
            password: ${{ secrets.NEXUS_PASSWORD }}
        - name: Set up Docker buildx
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              repo.m4ku0j.ru/docker-images/timer:${{ VERSION }}
              repo.m4ku0j.ru/docker-images/timer:latest



