name: Test some shit
run-name: "{{ gitea.actor }} is running test"
on: [push]
jobs:
  Run-unit-tests:
     runs-on: docker
     steps:
        - name: Check out repo code 
          uses: actions/checkout@v4
        - run: echo "Running npm run ci"
        - run: cd ${{ gitea.repository }}; npm ci
        - run: echo "Running tests"
        - run: npm run test

